version: "2"
checks:
  identical-code:
    enabled: false
  config:
    threshold: 4
  similar-code:
    enabled: false
  config:
    threshold: 4
  argument-count:
    enabled: true
    config:
      threshold: 4
  complex-logic:
    enabled: true
    config:
      threshold: 4
  file-lines:
    enabled: true
    config:
      threshold: 350
  method-complexity:
    enabled: true
    config:
      threshold: 15
  method-count:
    enabled: true
    config:
      threshold: 20
  method-lines:
    enabled: true
    config:
      threshold: 250
  nested-control-flow:
    enabled: true
    config:
      threshold: 4
  return-statements:
    enabled: true
    config:
      threshold: 5
plugins:
  eslint:
    enabled: true
exclude_patterns:
  - "node_modules/"
  - "config/"
  - "coverage/"
  - "test/"
  